apiVersion: batch/v1
kind: Job
metadata:
  name: cicd
  namespace: postgres
spec:
  completions: 3
  parallelism: 3
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: cicd
        image: cezeike39/docker:cicd
      restartPolicy: Never
