apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNz
  secret_access_key: bXZIbkQydGk2b2IzbGdHQ2ZHWTY1NGhSSllMMU9kc3VQUUdobVpkTQ==
  aws_access_key: QUtJQVdNRlVQTlE1SzZPU1dYUDY=
  

